export const CommonImages = {
  logo: require("../assets/logo.png"),
  electrition: require("../assets/electrcian.png"),
  manson: require("../assets/mason.png"),
  plumber: require("../assets/plumber.png"),
  welder: require("../assets/welder.png"),
  barber: require("../assets/barber.png"),
  location: require("../assets/Location.png"),
  rightarrow: require("../assets/rightarrow.png"),
  visa: require("../assets/Visa.png"),
  hrs: require("../assets/hrs.png"),
  timer: require("../assets/timer.png"),
  taskComp: require("../assets/taskComp.png"),
  creditcardbg: require("../assets/creditcardbg.png"),
};
