export { default as Home } from "./home/Index";
export { default as Login } from "./Login/Index";
export { default as Messages } from "./home/Messages";
export { default as StartLogin } from "./Login/Start";
export { default as SignUp } from "./Login/SignUp";
export { default as Forget } from "./Login/Forget";
export { default as Profile } from "./Profile/Index";
export { default as Wallet } from "./Wallet/Index";
export { default as Payment } from "./Wallet/Payment";
export { default as PaymentAdd } from "./Wallet/PaymentAdd";
export { default as Booking } from "./Booking/Index";
export { default as Detail } from "./Booking/Detail";
export { default as Menu } from "./Menu/Index";
export { default as Country } from "./Profile/Country";
export { default as CommunityGuidelines } from "./Menu/CommunityGuidelines";
export { default as TermsConditions } from "./Menu/TermsConditions";
export { default as Notification } from "./Notification/Index";
export { default as About } from "./Menu/About";
// export {default as Home} from './home/Home';
export { default as SplashScreen } from "./SplashScreen/index";
export { default as IntroScreen01 } from "./Onboarding/IntroScreen01";
export { default as IntroScreen02 } from "./Onboarding/IntroScreen02";
export { default as LogInScreen } from "./Onboarding/LogInScreen";
export { default as Pending } from "./Notification/Pending";
export { default as Application } from "./Notification/Application";
export { default as General } from "./Notification/General";
export { default as ForgotPswd } from "./Login/ForgotPswd";
export { default as NewPassword } from "./Login/NewPassword";
export { default as LocationBottomSheet } from "../components/LocationBottomSheet/index";
export { default as RateSupplierBSheet } from "../components/RateSupplierBSheet/Index";
export { default as Accepted} from '../screens/Booking/Accepted';

